server:
  port: 8090
  servlet:
    context-path: /oss

spring:
  #file配置
  servlet:
    multipart:
      max-file-size: 1024MB
      enabled: true
      max-request-size: 1024MB


oss:
  platform:
    local:
      enabled: true
    fdfs:
      enabled: true

#######存储配置设置#########
local:
  root: /Users/zhanghuan/Desktop/upload
  invokingRoot: 192.168.0.7

###FASTDFS CONFIG START###
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  thumb-image:
    height: 150
    width: 150
  tracker-list:
    - 10.0.46.130:44144
  http: 10.0.46.130:40002
  pool:
    jmx-enabled: false

#######存储配置设置#########